### ISSUE TITLE
Rick and Morty animated sticker pack

### ISSUE THREAD

**Issue by Hectorius99** [teynav/signalApngSticker#1]
First, I would like to thank you for your work and your script. Animated stickers are great! :)

I tried converting this pack:
https://t.me/addstickers/RickAndMorty
using the script but no success. There were no apng files in the output folder, just static png images.
Some potentially helpful lines from the terminal:
- tmp.png already at best
- warning: GIF too complex to unoptimize
  (The reason was local color tables or complex transparency.
  Try running the GIF through ‘gifsicle --colors=255’ first.)
  gifsicle: frame ‘#150’ out of range, image has 150 frames

Is it possible to convert these to Signal or are they just too complex/large? Or it might just be me doing something wrong.

**Comment by teynav** [comment]
Hey, I think you were misled by "png" extension and thought it isn't apng. Apng also have png extension.

They might be not animating because many different apps don't support apng yet. Can you import any of those files into Signal desktop sticker pack creator? Pretty sure it is animated.

**Comment by teynav** [comment]
And I checked the sticker packs I converted for Signal, I found this sticker pack I converted for Signal a month ago

https://signal.art/addstickers/#pack_id=d9972b04ad521cf093a92b4a5287a93e&pack_key=5f082cd8ed158672001c16fcb7e0e0f3df67f15220c9c82fce2a6f4646674b62

**Comment by tomasi-o** [comment]
> And I checked the sticker packs I converted for Signal, I found this sticker pack I converted for Signal a month ago
> 
> https://signal.art/addstickers/#pack_id=d9972b04ad521cf093a92b4a5287a93e&pack_key=5f082cd8ed158672001c16fcb7e0e0f3df67f15220c9c82fce2a6f4646674b62

You're a livesaver, Thank you :)
