### ISSUE TITLE
support for bash

### ISSUE THREAD

**Issue by fariszr** [teynav/signalApngSticker#2]
i have noticed that the script uses zsh.

its there any plans for compatibility with bash?

also tgs-to-gif requires npm?

**Comment by teynav** [comment]
I will have to refactor a lot of code for compatibility with bash, maybe with v3? 
I don't think tgs-to-gif requires npm, I don't have npm on my system but have tgs-to-gif

**Comment by teynav** [comment]
I am currently trying to make backup from unable to upload packs stable, after that I would work on making it compatible with bash!

**Comment by teynav** [comment]
Hey I have checked and update code, it's totally bash compatible now and uses /bin/bash , will change readme soon!
